update compile script to look for production_build_go

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -23,7 +23,7 @@ urlfor() {
     esac
 }
 
-# Expand to supported versions of Go, (e.g. expand "go1.5" to latest release go1.5.2)
+# Expand to supported versions of Go, (e.g. expand "go1.5" to latest release go1.5.3)
 # All specific or other versions, take as is.
 expand_ver() {
   case $1 in
@@ -95,45 +95,60 @@ finished() {
     echo "done"
 }
 
-if test -f $build/Godeps
+if ! test -f $build/production_build_go.json
 then
-    warn ""
-    warn "Deprecated, old ./Godeps file found!"
-    warn ""
-    warn "Support for this old version of Godeps is ending on 2016/02/01"
-    warn ""
-    warn "Please upgrade godeps (go get -u github.com/tools/godep) and"
-    warn "re-save your dependencies: godep save -r ./..."
-    warn ""
-    warn "See also: https://devcenter.heroku.com/articles/go-dependencies-via-godep"
-    warn ""
-    name=$(<$build/Godeps jq -r .ImportPath)
-    ver=$(<$build/Godeps jq -r .GoVersion)
-elif test -f $build/Godeps/Godeps.json
-then
-    step "Checking Godeps/Godeps.json file."
-    if ! jq -r . < $build/Godeps/Godeps.json > /dev/null
-    then
-        warn "Bad Godeps/Godeps.json file"
-        exit 1
-    fi
-    name=$(<$build/Godeps/Godeps.json jq -r .ImportPath)
-    ver=$(<$build/Godeps/Godeps.json jq -r .GoVersion)
-elif test -f $build/.godir
-then
-    warn ""
-    warn "Deprecated, .godir file found!"
-    warn ""
-    warn "Support for .godir is ending on 2016/02/01"
-    warn "See also: https://devcenter.heroku.com/articles/go-dependencies-via-godep"
-    warn ""
-    name=$(cat $build/.godir)
-    ver=go${GOVERSION:-1.5}
-else
-    warn "Godeps are required. For instructions:"
-    warn "https://devcenter.heroku.com/articles/go-support"
-    exit 1
+  warn "production_build_go_file is required"
+  exit 1
+elif
+  step "Checking production_build_go file."
+  if ! jq -r . < $build/production_build_go.json > /dev/null
+  then
+      warn "Bad production_build_go.json file"
+      exit 1
+  fi
+  name=$(<$build/production_build_go.json jq -r .Name)
+  ver=$(<$build/production_build_go.json jq -r .GoVersion)
 fi
+#
+# if test -f $build/Godeps
+# then
+#     warn ""
+#     warn "Deprecated, old ./Godeps file found!"
+#     warn ""
+#     warn "Support for this old version of Godeps is ending on 2016/02/01"
+#     warn ""
+#     warn "Please upgrade godeps (go get -u github.com/tools/godep) and"
+#     warn "re-save your dependencies: godep save -r ./..."
+#     warn ""
+#     warn "See also: https://devcenter.heroku.com/articles/go-dependencies-via-godep"
+#     warn ""
+#     name=$(<$build/Godeps jq -r .ImportPath)
+#     ver=$(<$build/Godeps jq -r .GoVersion)
+# elif test -f $build/Godeps/Godeps.json
+# then
+#     step "Checking Godeps/Godeps.json file."
+#     if ! jq -r . < $build/Godeps/Godeps.json > /dev/null
+#     then
+#         warn "Bad Godeps/Godeps.json file"
+#         exit 1
+#     fi
+#     name=$(<$build/Godeps/Godeps.json jq -r .ImportPath)
+#     ver=$(<$build/Godeps/Godeps.json jq -r .GoVersion)
+# elif test -f $build/.godir
+# then
+#     warn ""
+#     warn "Deprecated, .godir file found!"
+#     warn ""
+#     warn "Support for .godir is ending on 2016/02/01"
+#     warn "See also: https://devcenter.heroku.com/articles/go-dependencies-via-godep"
+#     warn ""
+#     name=$(cat $build/.godir)
+#     ver=go${GOVERSION:-1.5}
+# else
+#     warn "Godeps are required. For instructions:"
+#     warn "https://devcenter.heroku.com/articles/go-support"
+#     exit 1
+# fi
 
 ver=$(expand_ver $ver)
 
@@ -170,26 +185,26 @@ GOPATH=$build/.heroku/go export GOPATH
 PATH=$GOROOT/bin:$PATH
 
 
-if ! (test -d $build/Godeps || (which hg >/dev/null && which bzr >/dev/null))
-then
-    echo
-    echo "       Tired of waiting for bzr and hg?"
-    echo "       Use github.com/tools/godep for faster deploys."
-    echo
-
-    start "Installing Virtualenv"
-        virtualenv --python $python --distribute --never-download --prompt='(venv) ' $venv > /dev/null 2>&1
-        . $venv/bin/activate > /dev/null 2>&1
-    finished
-
-    start "Installing Mercurial"
-        pip install mercurial > /dev/null 2>&1
-    finished
-
-    start "Installing Bazaar"
-        pip install bzr > /dev/null 2>&1
-    finished
-fi
+# if ! (test -d $build/Godeps || (which hg >/dev/null && which bzr >/dev/null))
+# then
+#     echo
+#     echo "       Tired of waiting for bzr and hg?"
+#     echo "       Use github.com/tools/godep for faster deploys."
+#     echo
+#
+#     start "Installing Virtualenv"
+#         virtualenv --python $python --distribute --never-download --prompt='(venv) ' $venv > /dev/null 2>&1
+#         . $venv/bin/activate > /dev/null 2>&1
+#     finished
+#
+#     start "Installing Mercurial"
+#         pip install mercurial > /dev/null 2>&1
+#     finished
+#
+#     start "Installing Bazaar"
+#         pip install bzr > /dev/null 2>&1
+#     finished
+# fi
 
 p=$GOPATH/src/$name
 mkdir -p $p
@@ -212,43 +227,45 @@ then
     done
 fi
 
-if test -e $build/Godeps/Godeps.json
-then
-  pkgs=$(<$build/Godeps/Godeps.json jq -r 'if .Packages then .Packages | join(" ") else "." end')
-else
-  pkgs="./..."
-fi
+# if test -e $build/Godeps/Godeps.json
+# then
+#   pkgs=$(<$build/Godeps/Godeps.json jq -r 'if .Packages then .Packages | join(" ") else "." end')
+# else
+#   pkgs="./..."
+# fi
 
-case $ver in
-  go1.5*)
-    if test "$GO15VENDOREXPERIMENT" = "1"
-    then
-      warn ""
-      warn "\$GO15VENDOREXPERIMENT=1. This is an experiment. Things may not work as expected."
-      warn "See https://devcenter.heroku.com/articles/go-support#go-1-5-vendor-experiment for more info."
-      warn ""
-      if test ! -d "$build/vendor"
-      then
-        warn ""
-        warn "vendor/ directory does not exist."
-        warn ""
-        exit 1
-      fi
-      VendorExperiment="true"
-    fi
-  ;;
-  go1.6*)
-    if test "$GO15VENDOREXPERIMENT" = "0"
-    then
-      VendorExperiment="false"
-    else
-      VendorExperiment="true"
-    fi
-  ;;
-  *)
-    VendorExperiment="false"
-  ;;
-esac
+pkgs="./..."
+
+# case $ver in
+#   go1.5*)
+#     if test "$GO15VENDOREXPERIMENT" = "1"
+#     then
+#       warn ""
+#       warn "\$GO15VENDOREXPERIMENT=1. This is an experiment. Things may not work as expected."
+#       warn "See https://devcenter.heroku.com/articles/go-support#go-1-5-vendor-experiment for more info."
+#       warn ""
+#       if test ! -d "$build/vendor"
+#       then
+#         warn ""
+#         warn "vendor/ directory does not exist."
+#         warn ""
+#         exit 1
+#       fi
+#       VendorExperiment="true"
+#     fi
+#   ;;
+#   go1.6*)
+#     if test "$GO15VENDOREXPERIMENT" = "0"
+#     then
+#       VendorExperiment="false"
+#     else
+#       VendorExperiment="true"
+#     fi
+#   ;;
+#   *)
+#     VendorExperiment="false"
+#   ;;
+# esac
 
 # If $GO_LINKER_SYMBOL and GO_LINKER_VALUE are set, tell the linker to DTRT
 FLAGS=(-tags heroku)
@@ -267,20 +284,24 @@ fi
 
 unset GIT_DIR # unset git dir or it will mess with goinstall
 cd $p
-if test -e $build/Godeps
-then
-    if test "$VendorExperiment" = "true"
-    then
-      step "Running: go install -v ${FLAGS[@]} $pkgs"
-      go install -v "${FLAGS[@]}" $pkgs
-    else
-      step "Running: godep go install ${FLAGS[@]} $pkgs"
-      godep go install "${FLAGS[@]}" $pkgs
-    fi
-else
-    step "Running: go get ${FLAGS[@]} $pkgs"
-    go get "${FLAGS[@]}" $pkgs
-fi
+
+step "Running: go install -v ${FLAGS[@]} $pkgs"
+go install -v "${FLAGS[@]}" $pkgs
+
+# if test -e $build/Godeps
+# then
+#     if test "$VendorExperiment" = "true"
+#     then
+#       step "Running: go install -v ${FLAGS[@]} $pkgs"
+#       go install -v "${FLAGS[@]}" $pkgs
+#     else
+#       step "Running: godep go install ${FLAGS[@]} $pkgs"
+#       godep go install "${FLAGS[@]}" $pkgs
+#     fi
+# else
+#     step "Running: go get ${FLAGS[@]} $pkgs"
+#     go get "${FLAGS[@]}" $pkgs
+# fi
 
 rm -rf $build/.heroku
 
